= jMolecules - Architectural abstractions for Java

This repository contains libraries to help developers work with architectural concepts in Java.
It currently consists of the following artifacts.
These artifacts provide two purposes:

* Make it easy for the human reader to determine what kind of architectural concepts a given class is.
* Allow tool integration (to do interesting stuff like generating persistence or static architecture analysis to check for validations of the architectural rules.)

== Artifacts to express DDD concepts
When we take Ubiquitous Language serious, we want names (for classes, methods, etc.) that only contain words from the domain language.
That means the titles of the building blocks should not be part of the names.
So in a banking domain we don't want `BankAccountEntity`, `CurrencyVO` or even `AccountRepository` as types.
Instead we want `BankAccount`, `Currency` and `Accounts`.
Still we want to express that a given class (or other architectural element) is a special building block; i.e. uses a design pattern.
jMolecules provide a set of standard annotations (and alternatively interfaces) for the building blocks known from DDD.

Example:

```java
import org.jmolecules.ddd.annotation.*;

@Entity
public class BankAccount { /* ... */ }

@ValueObject
public class Currency { /* ... */ }

@Repository
public class Accounts { /* ... */ }
```

* link:jmolecules-ddd[`jmolecules-ddd`] -- annotations and interfaces to express DDD building blocks (value objects, entities, aggregate roots etc.) in code.
* link:jmolecules-events[`jmolecules-events`] -- annotations and interfaces to express the concept of events in code.

== Artifacts to express architectures
* link:jmolecules-architecture[`jmolecules-architecture`] -- annotations to express architectural styles in code.
** link:jmolecules-architecture/jmolecules-architecture-layered[`jmolecules-architecture-layered`] -- Layered architecture
*** `@DomainLayer`
*** `@ApplicationLayer`
*** `@InfrastuctureLayer`
*** `@InterfaceLayer`
** link:jmolecules-architecture/jmolecules-architecture-onion[`jmolecules-architecture-onion`] -- Onion architecture
*** **Classic**
**** `@DomainModelRing`
**** `@DomainServiceRing`
**** `@ApplicationServiceRing`
**** `@InfrastructureRing`
*** **Simplified** (does not separate domain model and services)
**** `@DomainRing`
**** `@ApplicationRing`
**** `@InfrastructureRing`

== Technology integration
* link:jmolecules-integration/jmolecules-archunit[`jmolecules-archunit`] -- ArchUnit rules that verify the aggregate structures in your model.
* link:jmolecules-integration/jmolecules-jpa[`jmolecules-jpa`] -- A ByteBuddy plugin to derive default JPA mappings for code that expresses DDD building blocks via `jmolecules-ddd`.
* link:jmolecules-integration/jmolecules-spring[`jmolecules-spring`] -- A ByteBuddy plugin to derive Spring component annotations for code that expresses DDD building blocks via `jmolecules-ddd`.

== Examples
* link:jmolecules-examples[`jmolecules-examples`] -- A collection of examples to showcase the usage of the concept types and annotations as well as the technology integration.

== Installation
To use jMolecules in your project just install it from the Maven central repository.

=== Maven

```xml
<dependency>
  <groupId>org.jmolecules</groupId>
  <artifactId>jmolecules-ddd</artifactId>
  <version>0.1.0</version>
</dependency>
```

=== Gradle

```groovy
compile("org.jmolecules:jmolecules-ddd:0.1.0")
```

== Release instructions

* `mvn release:prepare -DscmReleaseCommitComment="$ticketId - Release version $version." -DscmDevelopmentCommitComment="$ticketId - Prepare next development iteration."`
* `mvn release:perform`
