= jMolecules JPA integration

This module contains a https://bytebuddy.net/[ByteBuddy] plugin that will default JPA mapings for domain types using jMolecules annotations and interfaces.

== Context

If you want to map aggregates, entities and value objects to your database using JPA, you need quite a few boilerplate mappings and implementations to actually make the type work for JPA as is.
For example, `Identifier` implementations in JPA would need:

* be annotated with `@Embeddable`
* implement `Serializable`
* declare a default constructor
* the aggregate's property it's used in needs to be annotated with `@EmbeddedId`

== Features

The ByteBuddy plugin inspects the types being compiled and will automatically tweak the code as follows:

* Aggregates and entities are annotated with `@Entity`.
* Adds default constructors for aggregates, entities and `Identifier` implementations.
* Adds an `@PrePersist`, `@PreUpdate` and `@PostLoad` method to verify the fields declared non-nullable (using Spring's `@NonNullApi` / `@Nullable`).
* Aggregate references to entities are mapped using `@OneToOne` / `@OneToMany` (with `cascade = CascadeType.ALL`).
* References to ``Identifier``s are mapped as `@EmbeddedId`.
* `Identifier` implementations will be annotated with `@Embeddable`, implement `Serializable` and get a default constructor.

The annotation defaulting backs off as soon as one of the annotations is already present on the field or class.
That means you'd only add the annotations if you need to configure a custom mapping.
The following declarations make up completely working JPA entities (`@Value` and `@Getter` being Lombok annotations).

[source, java]
----
@Value
class OrderIdentifier implements Identifier {
  private final UUID id;
}

@Value
class CustomerIdentifier implements Identifier {
  private final UUID id;
}

class Order implements AggregateRoot<Order, OrderIdentifier> {

  private final @Getter OrderIdentifier id;
  private final CustomerIdentifier customer;
  private final List<LineItem> lineItems;

  Order(CustomerIdentifier customer) {
    this.id = new OrderIdentifier(UUID.randomUUID());
    this.customer = customer;
    this.lineItems = new ArrayList<>();
  }
}

class LineItem implements Entity<Order, Long> { /* … */ }
----

== Setup

In your project dependencies, add:

[source, xml]
----
<dependency>
  <groupId>org.jmolecules</groupId>
  <artifactId>jmolecules-jpa</artifactId>
  <version>${jmolecules.version}</version>
</dependency>
----

In the build section of your POM add the ByteBuddy Maven plugin and point it to the jMolecules ByteBuddy plugin:

[source, xml]
----
<plugin>
  <groupId>net.bytebuddy</groupId>
  <artifactId>byte-buddy-maven-plugin</artifactId>
  <version>${bytebuddy.version}</version>
  <executions>
    <execution>
      <goals>
        <goal>transform</goal> <1>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency> <2>
      <groupId>org.jmolecules</groupId>
      <artifactId>jmolecules-jpa-plugin</artifactId>
      <version>${jmolecules.version}</version>
    </dependency>
  </dependencies>
  <configuration>
    <transformations>
      <transformation>
        <plugin>org.jmolecules.jpa.plugin.JMoleculesJpaPlugin</plugin> <3>
      </transformation>
    </transformations>
  </configuration>
</plugin>
----
<1> Enable the plugin's `transform` goal.
<2> Declare the ByteBuddy jMolecules JPA plugin as dependency.
<3> Point it to the plugin class.

